spring.application.name=addressbookapp

logging.level.root=INFO
logging.level.com.bridgelabz.addressbookapp=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.name=addressbook.log
spring.profiles.active=dev
